spring:
  application:
    name: techefx-spring-cloud-config-server

  cloud:
    config:
      server:
        git: 
          uri: https://github.com/kirantyga1/external-properties.git
          
            

server:
  port: ${port:8888}